appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: h8tweS9sMnR8/9nXUjv1iW/w8EQfyaDwPajqKGiVa4qPyc3crHCYvd/tNGow1VwRqswhXp3jr6ZCUR/NDW1ethYAz+/WHy7O5szg/nIpRqeYJnELyko9nfcmclH3yjU829rXipa0lg5gqnbCoftbJljMNqUdM2JPWQpUMvOLCmgtTL+k2NFjO76soWGGlQFIwfaPFqw3pC7cAvUfKwjQYhD+sJHIGpAvPhFwOUalhKBL0DtAMSGolfBAoVzZvevuqFgqXpm80Vrdo8Bn2LMGtGFKFMBME8LegTdeSCvnopYsNZhzqExi9/ajX4zXm+7SgeBGCQTuUA4KVF1ZeOQORySNIxWGs5pITLv7Tn1p8Dez5+H/V1izfUlZZnirA93n1BZgGLHYH2aPv1ax7ZHkETTaPAUL+itamm2aBrdmCtZ24vix9HGHNoqEEjA/b6+SevIqaRccmtBBJwyV1j+j46D12PvnF4eHa5D+1xKw8aFBX5Nrm8W0qw3RNK7lJ956MBmfyL9GWVo6Wl2K+Ie49k5230egI8BRqRP9tBN/gwpi7Cp4zrIpRBLzK0gYzoXQrZgtYasfIgIy0sPRM9ASMd15rZtsOxpzdbCWPRrxeR1bvu9XMNozBpWNtQFxHkH/+zX7GAgw4sKcGS6mf++TF8ITal1LNkHmtLCGs2PqwpM=}
conda_forge_output_validation: true
